const INFO = {
  CVSummary: "Motivated professional transitioning from over a decade in the bike industry to software development, having successfully completed the Launch School curriculum. Skilled in object-oriented programming, problem-solving, and full-stack development, with hands-on experience building personal projects with today's technologies. I’m eager to apply my technical skills and a strong work ethic to contribute to innovative software solutions.",
  introduction: "I've always had a passion for learning and discovery. Figuring things out, taking things appart and seeing how they work, splitting problems into smaller chunks to find a solution. This relentless approach to learning first lead to an interest in consumer electronics, a brief (now 15 year career) in the bicycle industry, and now into the world of software.",
  story: "I've always loved learning and solving problems. This is a common theme when I'm reflecting on myself. Ever since I was a child I've searched for the `How?`. Determining how something worked, then implementing my own version of it. <br><br> While working my initial career in consumer electronics after a fascination with all things tech doing home theatre installations, computer builds, etc., I fell back in love with Cycling. The required dedication and self discipline to compete at any level drew me in and I was hooked. The mechanical side of the sport was a passion as well, with electronic shifting and more technology moving into the equipment as I continued riding. I was sucked into the industry completely and have worked my way up from store staff to now working for a brand in a wholesale capacity. <br><br>Throughout this time, I started to run into situations in my day to day tasks that were ripe for effeciency improvements. I started with Excel macros, but quickly ran into situations where I was interacting with different software within a task. Thinking there had to be a better way, I started looking into more complex solutions, more often than not resulting in writing scrips to complete the task.<br><br>This sparked the interest to learn software engineering I began researching my options. I settled on Launch School, a mastery based program focused on the fundamentals. Using Ruby and JavaScript, the program teaches the principals like object oriented programming, problem solving, and full-stack development. After completing the course, I continued my learning while working on personal projects to show my abilities.",
  code: "<b>My approach to writing code</b> is to take a structured approach. I start by determining the problem at hand, the variables involved, and creating a plan. Tackle the problem, work on getting a first draft of a solution providing project. Afterwards, spend ample time on refactoring. Cleaning up the code, ensuring clarity for others, and looking for any optimizations. I strive to write maintainable, effecient code, spending time to help others be able to quickly be able to digest my approach.",
  problems: "<b>I approach problems with curiosity</b> and break them down. Viewing the problem as a whole, explore different solutions, and breaking the problem down allows me to tackle individual problems, rather than an issue as a whole. This helps identifying parts of a problem where a solution may already exist, or an option is available that can be iterated on.",
  clean: "<b>Writing clean code helps everyone.</b> I aim to write clean code, maintainable code. This allows for a sustainable and adaptable code easily digestible by co-contributors.",
  thePerson: "I'm <b>resourceful</b> and like working to find solutions by using the tools and resources availalbe to me. I approach projects with an open mind, allowing me to entertain all possible solutions for a given issue. <br><br>I'm <b>curious</b>, a passion for learning lead me to software engineering, and this same curiosity enables me to constanty searc for new and innovative approaches to solve both new and existing problems.",
  theColleage: "",
}

export { INFO };